In [237]:
#Mòdul 3 - Programació numèrica, dataframes i anàlisi estadístic
#Importem les llibreries NUMPY i PANDAS i les carreguem a les variables np i pd respectivament
import numpy as np
import pandas as pd

In [238]:
# Crear una matrix de 3x3
matriz = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [239]:
matriz_b = [[1,2,3], [4,5,6], [7,8,9]]
matriz_b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [240]:
#Una altra forma de crear una matriu amb valors al·leatoris
import random
matriz1 = np.random.randint(1,10, size=(3,3))
matriz1

array([[4, 2, 2],
       [3, 3, 2],
       [4, 9, 5]])

In [241]:
#Accedir a un element d'una matriu (compte! comença amb 0)
matriz[2,2]

9

In [242]:
matriz[-1,-1]

9

In [243]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
#Totes les files, columna 1
matriz[:,1]

array([2, 5, 8])

In [245]:
#fila 1, totes les columnes
matriz[1,:]

array([4, 5, 6])

In [246]:
#fila 0, columna 0
matriz[0,0]

1

In [247]:
# Una copia RELACIONADA >> tots els canvis que faci en una afectaran a l'altra
new = matriz

In [248]:
new[0,0]=0
matriz

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [249]:
# Copia de matrius NO RELACIONADES >> els canvis d'una NO afecten a l'altra
new = matriz.copy()
new[0,0]=23
matriz

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [250]:
new

array([[23,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [251]:
#
import random
matriz1 = np.random.randint(1,10, size=(2,5))
matriz1

array([[7, 7, 4, 6, 7],
       [9, 1, 7, 1, 2]])

In [252]:
#Trasposta d'una matriu
matriz1.reshape(5,2)

array([[7, 7],
       [4, 6],
       [7, 9],
       [1, 7],
       [1, 2]])

In [253]:
matriz4 = np.random.randint(1,10,size=(5,5))
matriz4

array([[5, 6, 1, 5, 3],
       [9, 5, 3, 9, 2],
       [8, 7, 3, 6, 1],
       [2, 5, 1, 8, 3],
       [2, 4, 9, 1, 4]])

In [254]:
#La mitjana dels valors d'un eix
matriz.mean(axis=1)

array([1.66666667, 5.        , 8.        ])

In [255]:
matriz.sort()
matriz

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [256]:
#valors de la columna 2
matriz[:,2]

array([3, 6, 9])

In [257]:
################ PANDAS #################
#Crear un dataframe buit amb nom df
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [258]:
# Creem tres llistes
nombre = ['Juan', 'José', 'Ana']
apellido = ['Sánchez', 'González', 'García']
edad = [18, 45, 72]



In [259]:
# Creem el dataframe com feien amb els diccionaris
df['Nombre'] = nombre
df

Nombre
0   Juan
1   José
2    Ana

In [260]:
df['Apellido'] = apellido
df['Edad'] = edad
df

Nombre  Apellido  Edad
0   Juan   Sánchez    18
1   José  González    45
2    Ana    García    72

In [261]:
# Altra forma de crear un dataframe 
df1 = pd.DataFrame([nombre, apellido,edad], index = ['Nombre','Apellido', 'Edad']).transpose()
df1

Nombre  Apellido Edad
0   Juan   Sánchez   18
1   José  González   45
2    Ana    García   72

In [262]:
# Compte!! No surt al mateix quan utilitzem columns 
df1 = pd.DataFrame([nombre, apellido,edad], columns = ['Nombre','Apellido', 'Edad'])
df1

Nombre  Apellido    Edad
0     Juan      José     Ana
1  Sánchez  González  García
2       18        45      72

In [263]:
#Una selecció de files
df[df['Edad']>50]

Nombre Apellido  Edad
2    Ana   García    72

In [264]:
#Amb això no aconsegui que cada element de la llista sigui una fila
[nombre, apellido, edad]

[['Juan', 'José', 'Ana'], ['Sánchez', 'González', 'García'], [18, 45, 72]]

In [265]:
# Una altra forma de crear una dataframe amb list(zip()) i columns
#Ara sí: cada element de la llista es una fila
list(zip (nombre, apellido, edad))

[('Juan', 'Sánchez', 18), ('José', 'González', 45), ('Ana', 'García', 72)]

In [266]:
# I ara amb dataframe i columns ja podem crear-lo
df1=pd.DataFrame(list(zip (nombre, apellido, edad)),columns = ['Nombre', 'Apellido', 'Edad'])
df1

Nombre  Apellido  Edad
0   Juan   Sánchez    18
1   José  González    45
2    Ana    García    72

In [267]:
#Crear dataframe desde un diccionario
compra = {'Pomes': {'Qty':5,'€':0.42},'Peres': {'Qty':3, '€':0.66}}
compra

{'Pomes': {'Qty': 5, '€': 0.42}, 'Peres': {'Qty': 3, '€': 0.66}}

In [268]:
df3 = pd.DataFrame(compra)
df3

Pomes  Peres
Qty   5.00   3.00
€     0.42   0.66

In [269]:
#Frutes hauria de ser una columna >> fem pas a pas
df3.transpose()

Qty     €
Pomes  5.0  0.42
Peres  3.0  0.66

In [270]:
df3 = df3.transpose().reset_index()
df3

index  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [271]:
df3.columns

Index(['index', 'Qty', '€'], dtype='object')

In [272]:
df3.columns = ['Fruita', 'Qty', '€']
df3

Fruita  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [273]:
df3 = df3.rename(columns = {'Fruita':'Fruit'})
df3

Fruit  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [274]:
#Podem crear dataframes a partir de fitxers de tot tipus: csv, json, excel, parquet...
# df = pd.read_csv
# df = pd.read_json

In [275]:
# Visualización de un dataframe
# Con head() nos da las cinco primeras filas, por defecto. O podemos pedir los diez primeros con head(10)
df.head()

Nombre  Apellido  Edad
0   Juan   Sánchez    18
1   José  González    45
2    Ana    García    72

In [276]:
#Acceder a las filas
#df.loc['nom'] para el nombre de índice
#df.iloc[num] pra el número de índice
df.loc[1]

Nombre          José
Apellido    González
Edad              45
Name: 1, dtype: object

In [277]:
#Acceder a las columnas
df['Apellido']

0     Sánchez
1    González
2      García
Name: Apellido, dtype: object

In [278]:
df.Apellido


0     Sánchez
1    González
2      García
Name: Apellido, dtype: object

# 3a sessió

In [279]:
df

Nombre  Apellido  Edad
0   Juan   Sánchez    18
1   José  González    45
2    Ana    García    72

In [280]:
df.head()

Nombre  Apellido  Edad
0   Juan   Sánchez    18
1   José  González    45
2    Ana    García    72

In [281]:
# Creamos un dataframe a partir d'un fitxer csv
df = pd.read_csv('train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [282]:
# con el head() tenemos las 5 primeras filas del dataframe
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [283]:
#  Acceso a los datos del dataframe
# Con el loc podemos acceder a filas o columnas con sus NOMBRES
#
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [284]:
# También con iloc (se mueve con los ÍNDICES)
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [285]:
#Acceso a columna con su nombre
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [286]:
# De la fila 9 en adelante, la columna Age
df.loc[9:,'Age']

9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 882, dtype: float64

In [287]:
# Todas las filas, la columna de nombre 0
df.iloc[:, 0]

0        1
1        2
2        3
3        4
4        5
      ... 
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [288]:
# con at una celda concreta con nombres
df.at[2,'Age']

26.0

In [289]:
# con iat igual que at, una celda concreta, pero con los índices
df.iat[2,0]

3

In [290]:
#acceder a una objeto de objeto >> con el doble corchete >> columna 'Age', posición 0
df['Age'][0]

22.0

In [291]:
# Dos filas concretas de una columna
df.loc[[0,2],'Age']

0    22.0
2    26.0
Name: Age, dtype: float64

In [292]:
#Todas las filas pero al revés
df[::-1]

PassengerId  Survived  Pclass  \
890          891         0       3   
889          890         1       1   
888          889         0       3   
887          888         1       1   
886          887         0       2   
..           ...       ...     ...   
4              5         0       3   
3              4         1       1   
2              3         1       3   
1              2         1       1   
0              1         0       3   

                                                  Name     Sex   Age  SibSp  \
890                                Dooley, Mr. Patrick    male  32.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
..                                                 ...     ...   ...    ...   
4                             Allen, Mr. William Henry    male  35.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
0                              Braund, Mr. Owen Harris    male  22.0      1   

     Parch            Ticket     Fare Cabin Embarked  
890      0            370376   7.7500   NaN        Q  
889      0            111369  30.0000  C148        C  
888      2        W./C. 6607  23.4500   NaN        S  
887      0            112053  30.0000   B42        S  
886      0            211536  13.0000   NaN        S  
..     ...               ...      ...   ...      ...  
4        0            373450   8.0500   NaN        S  
3        0            113803  53.1000  C123        S  
2        0  STON/O2. 3101282   7.9250   NaN        S  
1        0          PC 17599  71.2833   C85        C  
0        0         A/5 21171   7.2500   NaN        S  

[891 rows x 12 columns]

In [293]:
# Todas las filas y las columnas desde la 0 a la 2 
df.iloc[:, :2]

PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [294]:
# Filtros en Pandas: nombre del df [filtro]  Dentro de los corchetes, el filtro, será la condición de selección
df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [295]:
# Las filas que el Sex sea male
df[df['Sex'] == 'male']

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [296]:
# Dos condiciones >> Ojo poner los paréntesis para anidar condiciones lógicas
df[(df['Sex'] == 'male') & (df['Fare'] > 50)]

PassengerId  Survived  Pclass                                  Name  \
6              7         0       1               McCarthy, Mr. Timothy J   
27            28         0       1        Fortune, Mr. Charles Alexander   
34            35         0       1               Meyer, Mr. Edgar Joseph   
35            36         0       1        Holverson, Mr. Alexander Oskar   
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
..           ...       ...     ...                                   ...   
802          803         1       1   Carter, Master. William Thornton II   
826          827         0       3                          Lam, Mr. Len   
838          839         1       3                       Chip, Mr. Chang   
846          847         0       3              Sage, Mr. Douglas Bullen   
867          868         0       1  Roebling, Mr. Washington Augustus II   

      Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
6    male  54.0      0      0     17463   51.8625          E46        S  
27   male  19.0      3      2     19950  263.0000  C23 C25 C27        S  
34   male  28.0      1      0  PC 17604   82.1708          NaN        C  
35   male  42.0      1      0    113789   52.0000          NaN        S  
54   male  65.0      0      1    113509   61.9792          B30        C  
..    ...   ...    ...    ...       ...       ...          ...      ...  
802  male  11.0      1      2    113760  120.0000      B96 B98        S  
826  male   NaN      0      0      1601   56.4958          NaN        S  
838  male  32.0      0      0      1601   56.4958          NaN        S  
846  male   NaN      8      2  CA. 2343   69.5500          NaN        S  
867  male  31.0      0      0  PC 17590   50.4958          A24        S  

[73 rows x 12 columns]

In [297]:
# Guardamos en otra variable el resutlado
df1 = df[(df['Sex'] == 'male') & (df['Fare'] > 50)]
df1

PassengerId  Survived  Pclass                                  Name  \
6              7         0       1               McCarthy, Mr. Timothy J   
27            28         0       1        Fortune, Mr. Charles Alexander   
34            35         0       1               Meyer, Mr. Edgar Joseph   
35            36         0       1        Holverson, Mr. Alexander Oskar   
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
..           ...       ...     ...                                   ...   
802          803         1       1   Carter, Master. William Thornton II   
826          827         0       3                          Lam, Mr. Len   
838          839         1       3                       Chip, Mr. Chang   
846          847         0       3              Sage, Mr. Douglas Bullen   
867          868         0       1  Roebling, Mr. Washington Augustus II   

      Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
6    male  54.0      0      0     17463   51.8625          E46        S  
27   male  19.0      3      2     19950  263.0000  C23 C25 C27        S  
34   male  28.0      1      0  PC 17604   82.1708          NaN        C  
35   male  42.0      1      0    113789   52.0000          NaN        S  
54   male  65.0      0      1    113509   61.9792          B30        C  
..    ...   ...    ...    ...       ...       ...          ...      ...  
802  male  11.0      1      2    113760  120.0000      B96 B98        S  
826  male   NaN      0      0      1601   56.4958          NaN        S  
838  male  32.0      0      0      1601   56.4958          NaN        S  
846  male   NaN      8      2  CA. 2343   69.5500          NaN        S  
867  male  31.0      0      0  PC 17590   50.4958          A24        S  

[73 rows x 12 columns]

In [298]:
# Todas las filas, solo dos columnas
df.loc[:, ['PassengerId','Age']]

PassengerId   Age
0              1  22.0
1              2  38.0
2              3  26.0
3              4  35.0
4              5  35.0
..           ...   ...
886          887  27.0
887          888  19.0
888          889   NaN
889          890  26.0
890          891  32.0

[891 rows x 2 columns]

In [299]:
# Cómo acceder a las columnas. Dos formas:
df.Age


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [300]:
# Cómo acceder a las columnas. Dos formas:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [301]:
# Crear un dataframe a partir de listas
data = [[1,2,3],[4,5,6]]
columnas = ['x','y','z']
indices = ['a','b']
df = pd.DataFrame(data, columns = columnas, index = indices)
df

x  y  z
a  1  2  3
b  4  5  6

In [302]:
# Cambiamos el nombre de los índices
df.index = ['A','B']
df

x  y  z
A  1  2  3
B  4  5  6

In [303]:
# Cambiar nombre de las columnas con función rename
df = df.rename(columns={'x':'X', 'y':'Y'})
df

X  Y  z
A  1  2  3
B  4  5  6

In [304]:
df

X  Y  z
A  1  2  3
B  4  5  6

In [305]:
# Resetear índice a 0..n y crea nueva columna con los índice anteriores
df.reset_index()

index  X  Y  z
0     A  1  2  3
1     B  4  5  6

In [306]:
# podemos resetear y eliminar la columna que crea. Con inplace lo almacena en la variable
df.reset_index(drop=True, inplace=True)
df

X  Y  z
0  1  2  3
1  4  5  6

In [307]:
# Creamos un dataframe a partir de listas
df = pd.DataFrame(
    [[35,'teacher'],
     [31,'doctor'],
     [47, 'journalist'],
     [43,'nurse'],
     [20,'cafetero']],
     index = ['Maria', 'Fernando', 'Óscar', 'Josep', 'Adriana'],
     columns = ['age','profession']
)

df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [308]:
#Tamaño del dataframe: número de filas x número de columnas
df.shape


(5, 2)

In [309]:
# Info detallada del dataframe: número de filas, las columas y sus tipos (todo lo que no es numérico en dataframe serán de tipo object)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Maria to Adriana
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         5 non-null      int64 
 1   profession  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 120.0+ bytes


In [310]:
# Sumamos 2 a la edad de TODAS las fials
df.age + 2

Maria       37
Fernando    33
Óscar       49
Josep       45
Adriana     22
Name: age, dtype: int64

In [311]:
# Para que se guarde el resultado de la operación
df.age = df.age + 2
df

age  profession
Maria      37     teacher
Fernando   33      doctor
Óscar      49  journalist
Josep      45       nurse
Adriana    22    cafetero

In [312]:
# Restar
df.age - 1

Maria       36
Fernando    32
Óscar       48
Josep       44
Adriana     21
Name: age, dtype: int64

In [313]:
# Concatenar
df.profession + 'aaaa'

Maria          teacheraaaa
Fernando        doctoraaaa
Óscar       journalistaaaa
Josep            nurseaaaa
Adriana       cafeteroaaaa
Name: profession, dtype: object

In [314]:
# Multiplicar un string, lo repite
'casa' * 3

'casacasacasa'

In [315]:
df.profession*2

Maria             teacherteacher
Fernando            doctordoctor
Óscar       journalistjournalist
Josep                 nursenurse
Adriana         cafeterocafetero
Name: profession, dtype: object

In [316]:
# Al dividir, automáticamente se convierte en Flotante
df.age / 3

Maria       12.333333
Fernando    11.000000
Óscar       16.333333
Josep       15.000000
Adriana      7.333333
Name: age, dtype: float64

In [317]:
# Función módulo
df.age % 2

Maria       1
Fernando    1
Óscar       1
Josep       1
Adriana     0
Name: age, dtype: int64

In [318]:
# Filtro de igualdad
df.age == 35

Maria       False
Fernando    False
Óscar       False
Josep       False
Adriana     False
Name: age, dtype: bool

In [319]:
# Ver las filas que cumplen un filtro de no igualdad
df[df.age != 35]

age  profession
Maria      37     teacher
Fernando   33      doctor
Óscar      49  journalist
Josep      45       nurse
Adriana    22    cafetero

In [320]:
# Con ~ es el NOT (inverso)
~(df.age > 36)

Maria       False
Fernando     True
Óscar       False
Josep       False
Adriana      True
Name: age, dtype: bool

In [321]:
# Operador de inclusión ANY
(df.profession == 'teacher').any()

True

In [322]:
# Operador de inclusión ALL. ¿Todos tienen igual o más de 20 años?
(df.age >= 20).all()

True

In [323]:
df1

PassengerId  Survived  Pclass                                  Name  \
6              7         0       1               McCarthy, Mr. Timothy J   
27            28         0       1        Fortune, Mr. Charles Alexander   
34            35         0       1               Meyer, Mr. Edgar Joseph   
35            36         0       1        Holverson, Mr. Alexander Oskar   
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
..           ...       ...     ...                                   ...   
802          803         1       1   Carter, Master. William Thornton II   
826          827         0       3                          Lam, Mr. Len   
838          839         1       3                       Chip, Mr. Chang   
846          847         0       3              Sage, Mr. Douglas Bullen   
867          868         0       1  Roebling, Mr. Washington Augustus II   

      Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
6    male  54.0      0      0     17463   51.8625          E46        S  
27   male  19.0      3      2     19950  263.0000  C23 C25 C27        S  
34   male  28.0      1      0  PC 17604   82.1708          NaN        C  
35   male  42.0      1      0    113789   52.0000          NaN        S  
54   male  65.0      0      1    113509   61.9792          B30        C  
..    ...   ...    ...    ...       ...       ...          ...      ...  
802  male  11.0      1      2    113760  120.0000      B96 B98        S  
826  male   NaN      0      0      1601   56.4958          NaN        S  
838  male  32.0      0      0      1601   56.4958          NaN        S  
846  male   NaN      8      2  CA. 2343   69.5500          NaN        S  
867  male  31.0      0      0  PC 17590   50.4958          A24        S  

[73 rows x 12 columns]

In [324]:
#operador eq entre dos dataframes
df.eq(df1)

Age  Cabin  Embarked   Fare   Name  Parch  PassengerId  Pclass  \
6         False  False     False  False  False  False        False   False   
27        False  False     False  False  False  False        False   False   
34        False  False     False  False  False  False        False   False   
35        False  False     False  False  False  False        False   False   
54        False  False     False  False  False  False        False   False   
...         ...    ...       ...    ...    ...    ...          ...     ...   
Adriana   False  False     False  False  False  False        False   False   
Fernando  False  False     False  False  False  False        False   False   
Josep     False  False     False  False  False  False        False   False   
Maria     False  False     False  False  False  False        False   False   
Óscar     False  False     False  False  False  False        False   False   

            Sex  SibSp  Survived  Ticket    age  profession  
6         False  False     False   False  False       False  
27        False  False     False   False  False       False  
34        False  False     False   False  False       False  
35        False  False     False   False  False       False  
54        False  False     False   False  False       False  
...         ...    ...       ...     ...    ...         ...  
Adriana   False  False     False   False  False       False  
Fernando  False  False     False   False  False       False  
Josep     False  False     False   False  False       False  
Maria     False  False     False   False  False       False  
Óscar     False  False     False   False  False       False  

[78 rows x 14 columns]

In [325]:
df2 = df
df2

age  profession
Maria      37     teacher
Fernando   33      doctor
Óscar      49  journalist
Josep      45       nurse
Adriana    22    cafetero

In [326]:
df2.age = df2.age + 5
df2

age  profession
Maria      42     teacher
Fernando   38      doctor
Óscar      54  journalist
Josep      50       nurse
Adriana    27    cafetero

In [327]:
df.eq(df2)

age  profession
Maria     True        True
Fernando  True        True
Óscar     True        True
Josep     True        True
Adriana   True        True

In [328]:
# Operadores estadísticos: mean(), median(), min(), max(), std(), var(), value_counts() >> cuenta de valores únicos, corr(), quantile(), describe()
df['profession'].value_counts()

profession
teacher       1
doctor        1
journalist    1
nurse         1
cafetero      1
Name: count, dtype: int64

In [329]:
df['altura'] = [165, 178, 163, 183, 151]
df

age  profession  altura
Maria      42     teacher     165
Fernando   38      doctor     178
Óscar      54  journalist     163
Josep      50       nurse     183
Adriana    27    cafetero     151

In [330]:
# Correlación entre dos columnas numéricas
df[['age','altura']].corr()

age   altura
age     1.00000  0.50994
altura  0.50994  1.00000

In [331]:
#Quartil
df['age'].quantile(0.25)

38.0

In [332]:
df['age'].sort_values()

Adriana     27
Fernando    38
Maria       42
Josep       50
Óscar       54
Name: age, dtype: int64

In [333]:
# Describe se utiliza mucho. Breve descripción estadística de nuestros datos numéricos
df.describe()

age      altura
count   5.00000    5.000000
mean   42.20000  168.000000
std    10.59245   12.727922
min    27.00000  151.000000
25%    38.00000  163.000000
50%    42.00000  165.000000
75%    50.00000  178.000000
max    54.00000  183.000000

In [334]:
# o traspuesta si tenemos muchas columnas
df.describe().T

count   mean        std    min    25%    50%    75%    max
age       5.0   42.2  10.592450   27.0   38.0   42.0   50.0   54.0
altura    5.0  168.0  12.727922  151.0  163.0  165.0  178.0  183.0

In [335]:
# para variables categóricas (el top es el mayor alfabéticamente; y freq el más frecuente - en nuestro caso, todos unos- )
df.profession.describe()

count           5
unique          5
top       teacher
freq            1
Name: profession, dtype: object

In [336]:
import numpy as np

In [337]:
#Datos que faltan NaN, None
#Creamos un dataframe a partir de un diccionario
dict = {'Col1':[0,1,2,np.nan,4,5,6,7], 'Col2':[1.2,5.5,7.7,np.nan,9.9,10,11,12], 'Col3':[None,'b','c','d','e','c','b','b']}
df3 = pd.DataFrame(dict)
df3

Col1  Col2  Col3
0   0.0   1.2  None
1   1.0   5.5     b
2   2.0   7.7     c
3   NaN   NaN     d
4   4.0   9.9     e
5   5.0  10.0     c
6   6.0  11.0     b
7   7.0  12.0     b

In [338]:
# Demanem info del nostre dataframe
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    7 non-null      float64
 1   Col2    7 non-null      float64
 2   Col3    7 non-null      object 
dtypes: float64(2), object(1)
memory usage: 324.0+ bytes


In [339]:
# Demanem els estadísticos
df3.describe()

Col1       Col2
count  7.000000   7.000000
mean   3.571429   8.185714
std    2.636737   3.762724
min    0.000000   1.200000
25%    1.500000   6.600000
50%    4.000000   9.900000
75%    5.500000  10.500000
max    7.000000  12.000000

In [340]:
# per saber quants nulls tenim en cada columna
df3.isnull().sum()

Col1    1
Col2    1
Col3    1
dtype: int64

In [341]:
# Al mateix amb aquesta altra funció
df3.isna().sum()

Col1    1
Col2    1
Col3    1
dtype: int64

In [342]:
#Per veure el nulls
df3.isnull()*1

Col1  Col2  Col3
0     0     0     1
1     0     0     0
2     0     0     0
3     1     1     0
4     0     0     0
5     0     0     0
6     0     0     0
7     0     0     0

In [343]:
#Per eliminar los valores perdidos >> Sustituirlos por la media, la moda, etc.
# En la Col1 sustituimos por la media
df3['Col1'].fillna(df3['Col1'].mean(), inplace=True)
df3

Col1  Col2  Col3
0  0.000000   1.2  None
1  1.000000   5.5     b
2  2.000000   7.7     c
3  3.571429   NaN     d
4  4.000000   9.9     e
5  5.000000  10.0     c
6  6.000000  11.0     b
7  7.000000  12.0     b

In [344]:
df3.isna().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [345]:
#En la Col2 lo haremos por interpolación (de los 2 valores más cercanos)
df3['Col2'].interpolate(inplace=True)
df3

Col1  Col2  Col3
0  0.000000   1.2  None
1  1.000000   5.5     b
2  2.000000   7.7     c
3  3.571429   8.8     d
4  4.000000   9.9     e
5  5.000000  10.0     c
6  6.000000  11.0     b
7  7.000000  12.0     b

In [346]:
# Para Col3 miramos las moda
df3.Col3.mode()

0    b
Name: Col3, dtype: object

In [347]:
# La guardamos en una lista
lista = df3.Col3.mode()
lista[0]

'b'

In [348]:
# Sustituimos los None de la Col3 por la moda
df3['Col3'].fillna(df3.Col3.mode().iloc[0],inplace=True)
df3

Col1  Col2 Col3
0  0.000000   1.2    b
1  1.000000   5.5    b
2  2.000000   7.7    c
3  3.571429   8.8    d
4  4.000000   9.9    e
5  5.000000  10.0    c
6  6.000000  11.0    b
7  7.000000  12.0    b

In [349]:
# Agrupaciones de Col 3 (tenemos 2 'b') >> con count()
df3.groupby('Col3')['Col1'].count()

Col3
b    4
c    2
d    1
e    1
Name: Col1, dtype: int64

In [350]:
# Agrupaciones de Col 3 (tenemos 2 'b') >> con sum()
df3.groupby('Col3')['Col2'].sum()

Col3
b    29.7
c    17.7
d     8.8
e     9.9
Name: Col2, dtype: float64

In [351]:
df3.groupby(['Col3','Col1']).mean()

Col2
Col3 Col1          
b    0.000000   1.2
     1.000000   5.5
     6.000000  11.0
     7.000000  12.0
c    2.000000   7.7
     5.000000  10.0
d    3.571429   8.8
e    4.000000   9.9

In [355]:
# Pivot table
df3.pivot_table(values='Col1', columns=['Col3','Col1'], aggfunc='mean')

Col3        b                                   c                 d        e
Col1 0.000000 1.000000 6.000000 7.000000 2.000000 5.000000 3.571429 4.000000
Col2      1.2      5.5     11.0     12.0      7.7     10.0      8.8      9.9

In [356]:
df3.pivot_table(values='Col1', columns='Col3', aggfunc='mean')

Col3    b    c         d    e
Col1  3.5  3.5  3.571429  4.0

In [360]:
#El aggregate
df3.groupby('Col3')['Col1'].agg(['count','sum','mean'])

count        sum      mean
Col3                            
b         4  14.000000  3.500000
c         2   7.000000  3.500000
d         1   3.571429  3.571429
e         1   4.000000  4.000000

In [361]:
#Mapeo de datos a través de una función. Restar 2 a la edad de dataframe df2
df2

age  profession  altura
Maria      42     teacher     165
Fernando   38      doctor     178
Óscar      54  journalist     163
Josep      50       nurse     183
Adriana    27    cafetero     151

In [365]:
def resta_edad(value):
    return value-2
df2.age = df2.age.map(resta_edad)
df2

age  profession  altura
Maria      38     teacher     165
Fernando   34      doctor     178
Óscar      50  journalist     163
Josep      46       nurse     183
Adriana    23    cafetero     151

In [363]:
#Asignaciones >> crear o modificar varias columnas al mismo tiempo
df2


age  profession  altura
Maria      42     teacher     165
Fernando   38      doctor     178
Óscar      54  journalist     163
Josep      50       nurse     183
Adriana    27    cafetero     151

In [367]:
df2 = df2.assign(experience = [10, 3, 19, 20, 1], children = [0, 1, 2, 0, 5], state = ['single', 'married','divorced','married','married'])
df2

age  profession  altura  experience  children     state
Maria      38     teacher     165          10         0    single
Fernando   34      doctor     178           3         1   married
Óscar      50  journalist     163          19         2  divorced
Josep      46       nurse     183          20         0   married
Adriana    23    cafetero     151           1         5   married

In [369]:
# Apply >> Aplica una función a una columna y sustituye su valor por el devuelto por la función
df2.age = df2.age.apply(resta_edad)
df2

age  profession  altura  experience  children     state
Maria      36     teacher     165          10         0    single
Fernando   32      doctor     178           3         1   married
Óscar      48  journalist     163          19         2  divorced
Josep      44       nurse     183          20         0   married
Adriana    21    cafetero     151           1         5   married

In [371]:
def estado_civil(value):
    if value == 'single':
        return 0
    elif value == 'married':
        return 1
    else:
        return 2
df2.state = df2.state.apply(estado_civil)
df2

age  profession  altura  experience  children  state
Maria      36     teacher     165          10         0      0
Fernando   32      doctor     178           3         1      1
Óscar      48  journalist     163          19         2      2
Josep      44       nurse     183          20         0      1
Adriana    21    cafetero     151           1         5      1

In [375]:
#concatenar dataframes, por filas o por columnas
#Creamos otro dataframe a partir de un diccionario
data={'age':[34],'profession':['teacher'],'experience':[4],'children':[1],'state':[2],'age_job':[3]}
df4 = pd.DataFrame(data)
df4


age profession  experience  children  state  age_job
0   34    teacher           4         1      2        3

In [377]:
#la columna que no existía en df2 la rellena con NaN. Por defecto lo hace por el axis 0 que es filas
df5 = pd.concat([df2,df4])
df5

age  profession  altura  experience  children  state  age_job
Maria      36     teacher   165.0          10         0      0      NaN
Fernando   32      doctor   178.0           3         1      1      NaN
Óscar      48  journalist   163.0          19         2      2      NaN
Josep      44       nurse   183.0          20         0      1      NaN
Adriana    21    cafetero   151.0           1         5      1      NaN
0          34     teacher     NaN           4         1      2      3.0

In [378]:
# Corregimos el índice que es 0 (la nueva fila concatenada de df4)
df5.reset_index(inplace=True)
df5

index  age  profession  altura  experience  children  state  age_job
0     Maria   36     teacher   165.0          10         0      0      NaN
1  Fernando   32      doctor   178.0           3         1      1      NaN
2     Óscar   48  journalist   163.0          19         2      2      NaN
3     Josep   44       nurse   183.0          20         0      1      NaN
4   Adriana   21    cafetero   151.0           1         5      1      NaN
5         0   34     teacher     NaN           4         1      2      3.0

In [ ]:
# La columna index se tiene que llamar Name; el valor 0 debería ser un nombre, y la columna age_job que tenía NaN deberíamos sustituirlos por algo.

In [379]:
# Combinaciones >> merge: inner (intersección), outer (unión), left (lo que no está en la derecha lo completa con NaN), right (al revés que left)
df2

age  profession  altura  experience  children  state
Maria      36     teacher     165          10         0      0
Fernando   32      doctor     178           3         1      1
Óscar      48  journalist     163          19         2      2
Josep      44       nurse     183          20         0      1
Adriana    21    cafetero     151           1         5      1

In [384]:
# he eliminado de df2 la columna 'altura' df2 = df2.drop('altura', axis=1)
df2

age  profession  experience  children  state
Maria      36     teacher          10         0      0
Fernando   32      doctor           3         1      1
Óscar      48  journalist          19         2      2
Josep      44       nurse          20         0      1
Adriana    21    cafetero           1         5      1

In [387]:
pd.merge(df5, df2, on='age',how='inner')

index  age profession_x  altura  experience_x  children_x  state_x  \
0     Maria   36      teacher   165.0            10           0        0   
1  Fernando   32       doctor   178.0             3           1        1   
2     Óscar   48   journalist   163.0            19           2        2   
3     Josep   44        nurse   183.0            20           0        1   
4   Adriana   21     cafetero   151.0             1           5        1   

   age_job profession_y  experience_y  children_y  state_y  
0      NaN      teacher            10           0        0  
1      NaN       doctor             3           1        1  
2      NaN   journalist            19           2        2  
3      NaN        nurse            20           0        1  
4      NaN     cafetero             1           5        1

In [388]:
pd.merge(df5, df2, on='age',how='outer')

index  age profession_x  altura  experience_x  children_x  state_x  \
0     Maria   36      teacher   165.0            10           0        0   
1  Fernando   32       doctor   178.0             3           1        1   
2     Óscar   48   journalist   163.0            19           2        2   
3     Josep   44        nurse   183.0            20           0        1   
4   Adriana   21     cafetero   151.0             1           5        1   
5         0   34      teacher     NaN             4           1        2   

   age_job profession_y  experience_y  children_y  state_y  
0      NaN      teacher          10.0         0.0      0.0  
1      NaN       doctor           3.0         1.0      1.0  
2      NaN   journalist          19.0         2.0      2.0  
3      NaN        nurse          20.0         0.0      1.0  
4      NaN     cafetero           1.0         5.0      1.0  
5      3.0          NaN           NaN         NaN      NaN

In [389]:
pd.merge(df5, df2, on='age',how='left')

index  age profession_x  altura  experience_x  children_x  state_x  \
0     Maria   36      teacher   165.0            10           0        0   
1  Fernando   32       doctor   178.0             3           1        1   
2     Óscar   48   journalist   163.0            19           2        2   
3     Josep   44        nurse   183.0            20           0        1   
4   Adriana   21     cafetero   151.0             1           5        1   
5         0   34      teacher     NaN             4           1        2   

   age_job profession_y  experience_y  children_y  state_y  
0      NaN      teacher          10.0         0.0      0.0  
1      NaN       doctor           3.0         1.0      1.0  
2      NaN   journalist          19.0         2.0      2.0  
3      NaN        nurse          20.0         0.0      1.0  
4      NaN     cafetero           1.0         5.0      1.0  
5      3.0          NaN           NaN         NaN      NaN

In [390]:
pd.merge(df5, df2, on='age',how='right')

index  age profession_x  altura  experience_x  children_x  state_x  \
0     Maria   36      teacher   165.0            10           0        0   
1  Fernando   32       doctor   178.0             3           1        1   
2     Óscar   48   journalist   163.0            19           2        2   
3     Josep   44        nurse   183.0            20           0        1   
4   Adriana   21     cafetero   151.0             1           5        1   

   age_job profession_y  experience_y  children_y  state_y  
0      NaN      teacher            10           0        0  
1      NaN       doctor             3           1        1  
2      NaN   journalist            19           2        2  
3      NaN        nurse            20           0        1  
4      NaN     cafetero             1           5        1

In [1]:
#