In [1]:
import numpy as np

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [9]:
matriz = np.array([[1,2,3],
                   [1,2,3],
                   [3,2,1]])
matriz

array([[1, 2, 3],
       [1, 2, 3],
       [3, 2, 1]])

In [7]:
type(matriz)

numpy.ndarray

In [10]:
matriz3 = [[1,2,3],
                   [1,2,3],
                   [3,2,1]]
matriz3

[[1, 2, 3], [1, 2, 3], [3, 2, 1]]

In [11]:
type(matriz3)

list

In [6]:
import random
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz1

array([[9, 5, 8],
       [7, 7, 6],
       [7, 8, 8]])

In [13]:
matriz1[-1, -1]

8

In [14]:
matriz1[-1][-1]

8

In [15]:
matriz1[0]

array([9, 5, 8])

In [16]:
matriz1[1:]

array([[7, 7, 6],
       [7, 8, 8]])

In [17]:
matriz1[:2]

array([[9, 5, 8],
       [7, 7, 6]])

In [18]:
matriz1[1, :]

array([7, 7, 6])

In [19]:
matriz1

array([[9, 5, 8],
       [7, 7, 6],
       [7, 8, 8]])

In [20]:

matriz1[:, 1]

array([5, 7, 8])

In [22]:
matriz1[1]

array([7, 7, 6])

In [23]:
matriz1[0,0]

9

In [24]:
new = matriz1

In [25]:
new[0,0]=0

In [26]:
matriz1

array([[0, 5, 8],
       [7, 7, 6],
       [7, 8, 8]])

In [27]:
new = matriz1.copy()

In [28]:
new[0,0]=3

In [29]:
matriz1

array([[0, 5, 8],
       [7, 7, 6],
       [7, 8, 8]])

In [30]:
new

array([[3, 5, 8],
       [7, 7, 6],
       [7, 8, 8]])

In [42]:
matriz1 = np.random.randint(1, 10, size=(5, 5))

In [32]:
matriz1

array([[2, 9, 4, 6, 1],
       [8, 2, 7, 2, 9]])

In [35]:
matriz1.reshape((5,2))

array([[2, 9],
       [4, 6],
       [1, 8],
       [2, 7],
       [2, 9]])

In [36]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
matriz1.astype(float)

array([[2., 9., 4., 6., 1.],
       [8., 2., 7., 2., 9.]])

In [43]:
matriz4 = np.random.randint(1, 10, size=(5, 5))

In [41]:
matriz1

array([[2, 9, 4, 6, 1],
       [8, 2, 7, 2, 9]])

In [44]:
np.dot(matriz1, matriz4)

array([[ 85, 151, 183, 146, 147],
       [ 75, 120, 132, 119, 114],
       [ 58,  83,  80,  58,  61],
       [ 47, 105, 151, 116, 116],
       [ 81, 117, 143, 116, 103]])

In [45]:
matriz + matriz1

ValueError: operands could not be broadcast together with shapes (3,3) (5,5) 

In [46]:
matriz1 + matriz4

array([[ 5, 10, 13, 13,  9],
       [ 5, 10, 13, 11, 14],
       [ 9,  7,  8,  3,  7],
       [ 5, 12, 10, 13,  8],
       [10,  9, 13,  7,  9]])

In [50]:
matriz.mean(axis=1)

array([2., 2., 2.])

In [51]:
matriz.sort()

In [52]:
matriz

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
matriz1

array([[3, 7, 6, 8, 6],
       [4, 6, 7, 2, 6],
       [2, 1, 6, 2, 5],
       [2, 6, 1, 9, 3],
       [9, 4, 7, 2, 4]])

In [60]:
np.bincount(matriz1[:,2])

array([0, 1, 0, 0, 0, 0, 2, 2], dtype=int64)

In [61]:
df = pd.DataFrame()

In [62]:
df

Empty DataFrame
Columns: []
Index: []

In [63]:
nombre = ['Juan', 'Jose', 'Ana']
apellido = ['Sanchez', 'Gonzalez', 'Garcia']
edad = [18, 45, 72]

In [65]:
df['Nombre'] = nombre
df

Nombre
0   Juan
1   Jose
2    Ana

In [67]:
df['Apellido'] = apellido
df['Edad'] = edad
df

Nombre  Apellido  Edad
0   Juan   Sanchez    18
1   Jose  Gonzalez    45
2    Ana    Garcia    72

In [77]:
df1 = pd.DataFrame([nombre, apellido, edad], index = ['Nombre', 'Apellido', 'Edad']).transpose()
df1

Nombre  Apellido Edad
0   Juan   Sanchez   18
1   Jose  Gonzalez   45
2    Ana    Garcia   72

In [82]:
list(zip(nombre, apellido, edad))

[('Juan', 'Sanchez', 18), ('Jose', 'Gonzalez', 45), ('Ana', 'Garcia', 72)]

In [83]:
df1 = pd.DataFrame(list(zip(nombre, apellido, edad)), columns= ['Nombre', 'Apellido', 'Edad'])
df1

Nombre  Apellido  Edad
0   Juan   Sanchez    18
1   Jose  Gonzalez    45
2    Ana    Garcia    72

In [78]:
df[df['Edad']>50]

Nombre Apellido  Edad
2    Ana   Garcia    72

In [85]:
df2 = pd.DataFrame(matriz1, columns=['N1','N2', 'N3', 'N4', 'N5'])

In [86]:
df2

N1  N2  N3  N4  N5
0   3   7   6   8   6
1   4   6   7   2   6
2   2   1   6   2   5
3   2   6   1   9   3
4   9   4   7   2   4

In [96]:
matriz[0,:]

array([1, 2, 3])

In [117]:
df2 = pd.DataFrame(matriz1, columns=list(matriz1[0,:]))
df2

3  7  6  8  6
0  3  7  6  8  6
1  4  6  7  2  6
2  2  1  6  2  5
3  2  6  1  9  3
4  9  4  7  2  4

In [118]:
df2 = df2[1:].reset_index(drop=True)

In [119]:

df2

3  7  6  8  6
0  4  6  7  2  6
1  2  1  6  2  5
2  2  6  1  9  3
3  9  4  7  2  4

In [120]:
compra = {'Pomes': {'Qty':5, '€': 0.42}, 
           'Peres': {'Qty':3, '€': 0.66}
            }

In [33]:
compra = {'Pomes': {'Qty':5, '€': 0.42}, 
           'Peres': {'Qty':3, '€': 0.66}
            }

In [34]:
df3 = pd.DataFrame(compra)
df3

Pomes  Peres
Qty   5.00   3.00
€     0.42   0.66

In [122]:
df3.transpose()

Qty     €
Pomes  5.0  0.42
Peres  3.0  0.66

In [123]:
df3 = df3.transpose().reset_index()
df3

index  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [126]:
df3.columns = ['Fruta', 'Qty',	'€']

In [127]:
df3

Fruta  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [128]:
df3.rename(columns = {'Fruta':'Frutas'})

Frutas  Qty     €
0  Pomes  5.0  0.42
1  Peres  3.0  0.66

In [3]:
df4 = pd.read_csv('train.csv')

In [4]:
df4

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [10]:
df5 = pd.read_json('C:/Users/alana.olivieri/Desktop/datos.json')

In [11]:
df5

Nombre  Edad    Departamento
0   Juan    42    Comunicación
1  Laura    40  Administración
2   Pepe    37          Ventas

In [17]:
df4.head(888)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
883                      Banfield, Mr. Frederick James    male  28.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
883      0  C.A./SOTON 34068  10.5000   NaN        S  
884      0   SOTON/OQ 392076   7.0500   NaN        S  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  

[888 rows x 12 columns]

In [18]:
df4.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [21]:
df4.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
df4[df4['Embarked'].isna()]

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
61   female  38.0      0      0  113572  80.0   B28      NaN  
829  female  62.0      0      0  113572  80.0   B28      NaN

In [23]:
df4['Embarked'].isna()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Embarked, Length: 891, dtype: bool

In [29]:
df4[df4['Survived']==1]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  

[342 rows x 12 columns]

In [28]:
df4['Survived'].sum()

342

In [31]:
df4.loc[889]

PassengerId                      890
Survived                           1
Pclass                             1
Name           Behr, Mr. Karl Howell
Sex                             male
Age                             26.0
SibSp                              0
Parch                              0
Ticket                        111369
Fare                            30.0
Cabin                           C148
Embarked                           C
Name: 889, dtype: object

In [35]:
df3

Pomes  Peres
Qty   5.00   3.00
€     0.42   0.66

In [47]:
df3.loc[:, 'Pomes']

Qty    5.00
€      0.42
Name: Pomes, dtype: float64

In [46]:
df3.iloc[1, 0]

0.42

In [48]:
df3['Pomes']

Qty    5.00
€      0.42
Name: Pomes, dtype: float64

In [49]:
df3.Pomes

Qty    5.00
€      0.42
Name: Pomes, dtype: float64

--------------------------------------

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('tallas.csv')

In [21]:
df

peso  sexo  altura  talla
0     55     0     150     35
1     59     1     159     38
2     60     0     162     40
3     40     0     145     34
4     39     0     142     33
5     60     1     166     41
6     63     1     167     42
7     42     0     138     34
8     51     0     149     36
9     58     0     157     38
10    54     1     154     39
11    62     0     163     39
12    63     1     165     42

In [24]:
df.head(10)

peso  sexo  altura  talla
0    55     0     150     35
1    59     1     159     38
2    60     0     162     40
3    40     0     145     34
4    39     0     142     33
5    60     1     166     41
6    63     1     167     42
7    42     0     138     34
8    51     0     149     36
9    58     0     157     38

In [25]:
df.loc[0]

peso       55
sexo        0
altura    150
talla      35
Name: 0, dtype: int64

In [26]:
df.iloc[0]

peso       55
sexo        0
altura    150
talla      35
Name: 0, dtype: int64

In [28]:
df.sexo

0     0
1     1
2     0
3     0
4     0
5     1
6     1
7     0
8     0
9     0
10    1
11    0
12    1
Name: sexo, dtype: int64

In [29]:
df['sexo']

0     0
1     1
2     0
3     0
4     0
5     1
6     1
7     0
8     0
9     0
10    1
11    0
12    1
Name: sexo, dtype: int64

In [31]:
df.loc[9:, 'peso']

9     58
10    54
11    62
12    63
Name: peso, dtype: int64

In [34]:
df.loc[2:4, 'peso']

2    60
3    40
4    39
Name: peso, dtype: int64

In [38]:
df.at[2, 'peso']

60

In [32]:
df.iloc[:, 0]

0     55
1     59
2     60
3     40
4     39
5     60
6     63
7     42
8     51
9     58
10    54
11    62
12    63
Name: peso, dtype: int64

In [39]:
df.iat[2, 0]

60

In [40]:
df.peso[2]

60

In [42]:
df['peso'][2]

60

In [43]:
df.loc[[0,2], 'peso']

0    55
2    60
Name: peso, dtype: int64

In [45]:
df.loc[9:, 'peso']

9     58
10    54
11    62
12    63
Name: peso, dtype: int64

In [46]:
df[::1]

peso  sexo  altura  talla
0     55     0     150     35
1     59     1     159     38
2     60     0     162     40
3     40     0     145     34
4     39     0     142     33
5     60     1     166     41
6     63     1     167     42
7     42     0     138     34
8     51     0     149     36
9     58     0     157     38
10    54     1     154     39
11    62     0     163     39
12    63     1     165     42

In [47]:
df[::-1]

peso  sexo  altura  talla
12    63     1     165     42
11    62     0     163     39
10    54     1     154     39
9     58     0     157     38
8     51     0     149     36
7     42     0     138     34
6     63     1     167     42
5     60     1     166     41
4     39     0     142     33
3     40     0     145     34
2     60     0     162     40
1     59     1     159     38
0     55     0     150     35

In [51]:
df.iloc[:, :2]

peso  sexo
0     55     0
1     59     1
2     60     0
3     40     0
4     39     0
5     60     1
6     63     1
7     42     0
8     51     0
9     58     0
10    54     1
11    62     0
12    63     1

In [52]:
df

peso  sexo  altura  talla
0     55     0     150     35
1     59     1     159     38
2     60     0     162     40
3     40     0     145     34
4     39     0     142     33
5     60     1     166     41
6     63     1     167     42
7     42     0     138     34
8     51     0     149     36
9     58     0     157     38
10    54     1     154     39
11    62     0     163     39
12    63     1     165     42

In [53]:
df['sexo'] == 0

0      True
1     False
2      True
3      True
4      True
5     False
6     False
7      True
8      True
9      True
10    False
11     True
12    False
Name: sexo, dtype: bool

In [54]:
df[df['sexo'] == 0]

peso  sexo  altura  talla
0     55     0     150     35
2     60     0     162     40
3     40     0     145     34
4     39     0     142     33
7     42     0     138     34
8     51     0     149     36
9     58     0     157     38
11    62     0     163     39

In [55]:
df[df['peso'] < 50]

peso  sexo  altura  talla
3    40     0     145     34
4    39     0     142     33
7    42     0     138     34

In [58]:
df[(df['sexo'] == 0) & (df['peso'] > 50)]

peso  sexo  altura  talla
0     55     0     150     35
2     60     0     162     40
8     51     0     149     36
9     58     0     157     38
11    62     0     163     39

In [59]:
(df['sexo'] == 0) & (df['peso'] > 50)

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10    False
11     True
12    False
dtype: bool

In [60]:
df_m = df[df['sexo'] == 1]
df_m

peso  sexo  altura  talla
1     59     1     159     38
5     60     1     166     41
6     63     1     167     42
10    54     1     154     39
12    63     1     165     42

In [61]:
df[df['altura'] % 2 == 0]

peso  sexo  altura  talla
0     55     0     150     35
2     60     0     162     40
4     39     0     142     33
5     60     1     166     41
7     42     0     138     34
10    54     1     154     39

In [62]:
df1 = df[['peso', 'sexo']]

In [63]:
df1

peso  sexo
0     55     0
1     59     1
2     60     0
3     40     0
4     39     0
5     60     1
6     63     1
7     42     0
8     51     0
9     58     0
10    54     1
11    62     0
12    63     1

In [64]:
df2 = df[['altura', 'talla']]
df2

altura  talla
0      150     35
1      159     38
2      162     40
3      145     34
4      142     33
5      166     41
6      167     42
7      138     34
8      149     36
9      157     38
10     154     39
11     163     39
12     165     42

In [65]:
df.loc[:, ['altura','talla']]

altura  talla
0      150     35
1      159     38
2      162     40
3      145     34
4      142     33
5      166     41
6      167     42
7      138     34
8      149     36
9      157     38
10     154     39
11     163     39
12     165     42

In [68]:
df.peso
df['peso']

0     55
1     59
2     60
3     40
4     39
5     60
6     63
7     42
8     51
9     58
10    54
11    62
12    63
Name: peso, dtype: int64

In [128]:
data = [[1,2,3],[4,5,6]]
columnas = ['x', 'y', 'z']
indices = ['a', 'b']

df = pd.DataFrame(data, columns=columnas, index=indices)

In [72]:
df

x  y  z
a  1  2  3
b  4  5  6

In [73]:
df.index = ['A', 'B']

In [74]:
df

x  y  z
A  1  2  3
B  4  5  6

In [79]:
df.rename(columns={'x':'X', 'y':'Y'}, inplace=True)

In [80]:
df

X  Y  z
A  1  2  3
B  4  5  6

In [127]:
df = df.rename(columns={'x':'X', 'y':'Y'})
df

X  Y  z
a  1  2  3
b  4  5  6

In [85]:
df.reset_index(drop=True, inplace=True)

In [86]:
df

X  Y  z
0  1  2  3
1  4  5  6

In [131]:
df = pd.DataFrame(
    [[35, 'teacher'],
     [31, 'doctor'],
     [47, 'journalist'],
     [43, 'nurse'],
     [20, 'cafetero']],
     index = ['Maria', 'Fernando', 'Óscar', 'Josep', 'Adriana'],
     columns = ['age', 'profession']
)

df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [94]:
df.shape

(5, 2)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Maria to Adriana
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         5 non-null      int64 
 1   profession  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 120.0+ bytes


In [95]:
df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [97]:
df.age + 1

Maria       36
Fernando    32
Óscar       48
Josep       44
Adriana     21
Name: age, dtype: int64

In [98]:
df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [99]:
df.age = df.age + 1

In [100]:
df

age  profession
Maria      36     teacher
Fernando   32      doctor
Óscar      48  journalist
Josep      44       nurse
Adriana    21    cafetero

In [101]:
df.age - 1

Maria       35
Fernando    31
Óscar       47
Josep       43
Adriana     20
Name: age, dtype: int64

In [102]:
df.profession + 'aaaa'

Maria          teacheraaaa
Fernando        doctoraaaa
Óscar       journalistaaaa
Josep            nurseaaaa
Adriana       cafeteroaaaa
Name: profession, dtype: object

In [103]:
'casa' * 3

'casacasacasa'

In [104]:
df.profession * 2

Maria             teacherteacher
Fernando            doctordoctor
Óscar       journalistjournalist
Josep                 nursenurse
Adriana         cafeterocafetero
Name: profession, dtype: object

In [105]:
df.age * 3

Maria       108
Fernando     96
Óscar       144
Josep       132
Adriana      63
Name: age, dtype: int64

In [106]:
df.age ** 3

Maria        46656
Fernando     32768
Óscar       110592
Josep        85184
Adriana       9261
Name: age, dtype: int64

In [107]:
df.age / 3

Maria       12.000000
Fernando    10.666667
Óscar       16.000000
Josep       14.666667
Adriana      7.000000
Name: age, dtype: float64

In [108]:
df.age % 3

Maria       0
Fernando    2
Óscar       0
Josep       2
Adriana     0
Name: age, dtype: int64

In [110]:
df.age == 36

Maria        True
Fernando    False
Óscar       False
Josep       False
Adriana     False
Name: age, dtype: bool

In [112]:
df[df.age != 36]

age  profession
Fernando   32      doctor
Óscar      48  journalist
Josep      44       nurse
Adriana    21    cafetero

In [117]:
df.age > 36

Maria       False
Fernando    False
Óscar        True
Josep        True
Adriana     False
Name: age, dtype: bool

In [120]:
~(df.age > 36)

Maria        True
Fernando     True
Óscar       False
Josep       False
Adriana      True
Name: age, dtype: bool

In [121]:
(df.profession == 'teacher').any()

True

In [123]:
(df.age > 20).all()

True

In [133]:
df1

x  y  z
a  1  2  3
b  4  5  6

In [132]:
df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [134]:
df.eq(df1)

age  profession      x      y      z
Adriana   False       False  False  False  False
Fernando  False       False  False  False  False
Josep     False       False  False  False  False
Maria     False       False  False  False  False
a         False       False  False  False  False
b         False       False  False  False  False
Óscar     False       False  False  False  False

In [135]:
df2 = df.copy()

In [136]:
df2.age = df.age + 2

In [137]:
df2

age  profession
Maria      37     teacher
Fernando   33      doctor
Óscar      49  journalist
Josep      45       nurse
Adriana    22    cafetero

In [138]:
df

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [139]:
df.eq(df2)

age  profession
Maria     False        True
Fernando  False        True
Óscar     False        True
Josep     False        True
Adriana   False        True

In [140]:
df['profession'].value_counts()

teacher       1
doctor        1
journalist    1
nurse         1
cafetero      1
Name: profession, dtype: int64

In [141]:
df['altura'] = [165, 178, 163, 183, 151]
df

age  profession  altura
Maria      35     teacher     165
Fernando   31      doctor     178
Óscar      47  journalist     163
Josep      43       nurse     183
Adriana    20    cafetero     151

In [142]:
df.corr()

C:\Users\alana.olivieri\AppData\Local\Temp\ipykernel_19492\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


age   altura
age     1.00000  0.50994
altura  0.50994  1.00000

In [147]:
df['age'].quantile(0.75)

43.0

In [145]:
df['age'].sort_values()

Adriana     20
Fernando    31
Maria       35
Josep       43
Óscar       47
Name: age, dtype: int64

In [150]:
df.describe()

age      altura
count   5.00000    5.000000
mean   35.20000  168.000000
std    10.59245   12.727922
min    20.00000  151.000000
25%    31.00000  163.000000
50%    35.00000  165.000000
75%    43.00000  178.000000
max    47.00000  183.000000

In [151]:
df.profession.describe()

count           5
unique          5
top       teacher
freq            1
Name: profession, dtype: object

In [152]:
import numpy as np

In [153]:
np.nan

nan

In [200]:
dict = {'Col1': [0,1,2, np.nan, 4, 5, 6, 7], 'Col2': [1.2, 5.5, 7.7, np.nan, 9.9, 10, 11, 12], 'Col3':[None, 'b', 'c', 'd', 'e', 'c', 'b', 'b']}
df3 = pd.DataFrame(dict)
df3

Col1  Col2  Col3
0   0.0   1.2  None
1   1.0   5.5     b
2   2.0   7.7     c
3   NaN   NaN     d
4   4.0   9.9     e
5   5.0  10.0     c
6   6.0  11.0     b
7   7.0  12.0     b

In [157]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    4 non-null      float64
 1   Col2    4 non-null      float64
 2   Col3    4 non-null      object 
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes


In [158]:
df3.describe()

Col1      Col2
count  4.000000  4.000000
mean   1.750000  6.075000
std    1.707825  3.713377
min    0.000000  1.200000
25%    0.750000  4.425000
50%    1.500000  6.600000
75%    2.500000  8.250000
max    4.000000  9.900000

In [160]:
df3.isnull().sum()

Col1    1
Col2    1
Col3    1
dtype: int64

In [161]:
df3.isna().sum()

Col1    1
Col2    1
Col3    1
dtype: int64

In [162]:
df3.isnull()*1

Col1  Col2  Col3
0     0     0     1
1     0     0     0
2     0     0     0
3     1     1     0
4     0     0     0

In [201]:
df3['Col1'].fillna(df3['Col1'].mean(), inplace=True)

In [178]:
df3

Col1  Col2  Col3
0  0.00   1.2  None
1  1.00   5.5     b
2  2.00   7.7     c
3  1.75   NaN     d
4  4.00   9.9     e

In [179]:
df3.isna().sum()

Col1    0
Col2    1
Col3    1
dtype: int64

In [180]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    5 non-null      float64
 1   Col2    4 non-null      float64
 2   Col3    4 non-null      object 
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes


In [202]:
df3['Col2'].interpolate(inplace=True)

In [184]:
df3

Col1  Col2  Col3
0  0.00   1.2  None
1  1.00   5.5     b
2  2.00   7.7     c
3  1.75   8.8     d
4  4.00   9.9     e

In [187]:
lista = df3.Col3.mode()
# lista[0]

0    b
1    c
2    d
3    e
Name: Col3, dtype: object

In [203]:
df3['Col3'].fillna(df3.Col3.mode().iloc[0], inplace=True)

In [204]:
df3

Col1  Col2 Col3
0  0.000000   1.2    b
1  1.000000   5.5    b
2  2.000000   7.7    c
3  3.571429   8.8    d
4  4.000000   9.9    e
5  5.000000  10.0    c
6  6.000000  11.0    b
7  7.000000  12.0    b

In [205]:
df3.groupby('Col3')['Col1'].count()

Col3
b    4
c    2
d    1
e    1
Name: Col1, dtype: int64

In [206]:
df3.groupby('Col3').mean()

Col1   Col2
Col3                 
b     3.500000  7.425
c     3.500000  8.850
d     3.571429  8.800
e     4.000000  9.900

In [207]:
df3.groupby(['Col3', 'Col1']).mean()

Col2
Col3 Col1          
b    0.000000   1.2
     1.000000   5.5
     6.000000  11.0
     7.000000  12.0
c    2.000000   7.7
     5.000000  10.0
d    3.571429   8.8
e    4.000000   9.9

In [209]:
df3.pivot_table(values='Col1', columns=['Col3', 'Col1'], aggfunc='mean')

Col3        b                                   c                 d        e
Col1 0.000000 1.000000 6.000000 7.000000 2.000000 5.000000 3.571429 4.000000
Col2      1.2      5.5     11.0     12.0      7.7     10.0      8.8      9.9

In [212]:
df3.pivot_table(values='Col1', columns='Col3', aggfunc='sum')

Col3     b    c         d    e
Col1  14.0  7.0  3.571429  4.0

In [214]:
df3.groupby('Col3')['Col1'].agg(['count', 'sum', 'mean'])

count        sum      mean
Col3                            
b         4  14.000000  3.500000
c         2   7.000000  3.500000
d         1   3.571429  3.571429
e         1   4.000000  4.000000

In [215]:
df2

age  profession
Maria      37     teacher
Fernando   33      doctor
Óscar      49  journalist
Josep      45       nurse
Adriana    22    cafetero

In [218]:
def resta_edad(value):
    return value-2

df2.age = df2.age.map(resta_edad)

In [219]:
df2

age  profession
Maria      35     teacher
Fernando   31      doctor
Óscar      47  journalist
Josep      43       nurse
Adriana    20    cafetero

In [220]:
df2 = df2.assign(experience = [10, 3, 19, 20, 1], children = [0, 1, 2, 0, 5], state = ['sigle', 'married', 'divorcied', 'married', 'married'])
df2

age  profession  experience  children      state
Maria      35     teacher          10         0      sigle
Fernando   31      doctor           3         1    married
Óscar      47  journalist          19         2  divorcied
Josep      43       nurse          20         0    married
Adriana    20    cafetero           1         5    married

In [221]:
df2.loc['Maria', 'state'] = 'single'

In [222]:
df2

age  profession  experience  children      state
Maria      35     teacher          10         0     single
Fernando   31      doctor           3         1    married
Óscar      47  journalist          19         2  divorcied
Josep      43       nurse          20         0    married
Adriana    20    cafetero           1         5    married

In [225]:
df2.age = df2.age.apply(resta_edad)

In [226]:
df2

age  profession  experience  children      state
Maria      33     teacher          10         0     single
Fernando   29      doctor           3         1    married
Óscar      45  journalist          19         2  divorcied
Josep      41       nurse          20         0    married
Adriana    18    cafetero           1         5    married

In [227]:
def estado_civil(value):
    if value == 'single':
        return 0
    elif value == 'married':
        return 1
    else:
        return 2
    
df2.state.apply(estado_civil)

Maria       0
Fernando    1
Óscar       2
Josep       1
Adriana     1
Name: state, dtype: int64

In [228]:
df2.state = df2.state.apply(estado_civil)
df2

age  profession  experience  children  state
Maria      33     teacher          10         0      0
Fernando   29      doctor           3         1      1
Óscar      45  journalist          19         2      2
Josep      41       nurse          20         0      1
Adriana    18    cafetero           1         5      1

In [236]:
data = {'age':[34], 'profession': ['teacher'], 'experience': [4], 'children': [1], 'state': [2], 'age_job': [3]}
data

{'age': [34],
 'profession': ['teacher'],
 'experience': [4],
 'children': [1],
 'state': [2],
 'age_job': [3]}

In [237]:
df4 = pd.DataFrame(data)
df4

age profession  experience  children  state  age_job
0   34    teacher           4         1      2        3

In [239]:
df5 = pd.concat([df2, df4])

In [240]:
df5

age  profession  experience  children  state  age_job
Maria      33     teacher          10         0      0      NaN
Fernando   29      doctor           3         1      1      NaN
Óscar      45  journalist          19         2      2      NaN
Josep      41       nurse          20         0      1      NaN
Adriana    18    cafetero           1         5      1      NaN
0          34     teacher           4         1      2      3.0

In [241]:
df5.reset_index(inplace=True)

In [242]:
df5

index  age  profession  experience  children  state  age_job
0     Maria   33     teacher          10         0      0      NaN
1  Fernando   29      doctor           3         1      1      NaN
2     Óscar   45  journalist          19         2      2      NaN
3     Josep   41       nurse          20         0      1      NaN
4   Adriana   18    cafetero           1         5      1      NaN
5         0   34     teacher           4         1      2      3.0

In [243]:
df2

age  profession  experience  children  state
Maria      33     teacher          10         0      0
Fernando   29      doctor           3         1      1
Óscar      45  journalist          19         2      2
Josep      41       nurse          20         0      1
Adriana    18    cafetero           1         5      1

In [249]:
pd.merge(df5, df2, on = 'age', how = 'left')

index  age profession_x  experience_x  children_x  state_x  age_job  \
0     Maria   33      teacher            10           0        0      NaN   
1  Fernando   29       doctor             3           1        1      NaN   
2     Óscar   45   journalist            19           2        2      NaN   
3     Josep   41        nurse            20           0        1      NaN   
4   Adriana   18     cafetero             1           5        1      NaN   
5         0   34      teacher             4           1        2      3.0   

  profession_y  experience_y  children_y  state_y  
0      teacher          10.0         0.0      0.0  
1       doctor           3.0         1.0      1.0  
2   journalist          19.0         2.0      2.0  
3        nurse          20.0         0.0      1.0  
4     cafetero           1.0         5.0      1.0  
5          NaN           NaN         NaN      NaN

In [250]:
pd.merge(df5, df2, on = 'age', how = 'right')

index  age profession_x  experience_x  children_x  state_x  age_job  \
0     Maria   33      teacher            10           0        0      NaN   
1  Fernando   29       doctor             3           1        1      NaN   
2     Óscar   45   journalist            19           2        2      NaN   
3     Josep   41        nurse            20           0        1      NaN   
4   Adriana   18     cafetero             1           5        1      NaN   

  profession_y  experience_y  children_y  state_y  
0      teacher            10           0        0  
1       doctor             3           1        1  
2   journalist            19           2        2  
3        nurse            20           0        1  
4     cafetero             1           5        1

In [251]:
df5

index  age  profession  experience  children  state  age_job
0     Maria   33     teacher          10         0      0      NaN
1  Fernando   29      doctor           3         1      1      NaN
2     Óscar   45  journalist          19         2      2      NaN
3     Josep   41       nurse          20         0      1      NaN
4   Adriana   18    cafetero           1         5      1      NaN
5         0   34     teacher           4         1      2      3.0

-------------------------------

In [ ]:
pip install scikit-learn

In [252]:
from sklearn.datasets import load_iris

In [253]:
iris = load_iris()
data = iris.data
target = iris.target

In [254]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [255]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [256]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [257]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [258]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [260]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [261]:
np.concatenate((data, target), axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [262]:
data.shape

(150, 4)

In [263]:
target.shape

(150,)

In [264]:
comb = np.concatenate((data, target.reshape(-1,1)), axis = 1)
comb

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [1]:
import pandas as pd

In [18]:
df = pd.read_csv('DelayedFlights.csv/DelayedFlights.csv')
df

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955   
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
3                 4  2008      1           3          4   1829.0        1755   
4                 5  2008      1           3          4   1940.0        1915   
...             ...   ...    ...         ...        ...      ...         ...   
1936753     7009710  2008     12          13          6   1250.0        1220   
1936754     7009717  2008     12          13          6    657.0         600   
1936755     7009718  2008     12          13          6   1007.0         847   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  \
0         2211.0        2225            WN        335  N712SW   
1         1002.0        1000            WN       3231  N772SW   
2          804.0         750            WN        448  N428WN   
3         1959.0        1925            WN       3920  N464WN   
4         2121.0        2110            WN        378  N726SW   
...          ...         ...           ...        ...     ...   
1936753   1617.0        1552            DL       1621  N938DL   
1936754    904.0         749            DL       1631  N3743H   
1936755   1149.0        1010            DL       1631  N909DA   
1936756   1446.0        1437            DL       1639  N646DL   
1936757   1413.0        1418            DL       1641  N908DL   

         ActualElapsedTime  CRSElapsedTime  AirTime  ArrDelay  DepDelay  \
0                    128.0           150.0    116.0     -14.0       8.0   
1                    128.0           145.0    113.0       2.0      19.0   
2                     96.0            90.0     76.0      14.0       8.0   
3                     90.0            90.0     77.0      34.0      34.0   
4                    101.0           115.0     87.0      11.0      25.0   
...                    ...             ...      ...       ...       ...   
1936753              147.0           152.0    120.0      25.0      30.0   
1936754              127.0           109.0     78.0      75.0      57.0   
1936755              162.0           143.0    122.0      99.0      80.0   
1936756              115.0           117.0     89.0       9.0      11.0   
1936757              123.0           135.0    104.0      -5.0       7.0   

        Origin Dest  Distance  TaxiIn  TaxiOut  Cancelled CancellationCode  \
0          IAD  TPA       810     4.0      8.0          0                N   
1          IAD  TPA       810     5.0     10.0          0                N   
2          IND  BWI       515     3.0     17.0          0                N   
3          IND  BWI       515     3.0     10.0          0                N   
4          IND  JAX       688     4.0     10.0          0                N   
...        ...  ...       ...     ...      ...        ...              ...   
1936753    MSP  ATL       906     9.0     18.0          0                N   
1936754    RIC  ATL       481    15.0     34.0          0                N   
1936755    ATL  IAH       689     8.0     32.0          0                N   
1936756    IAD  ATL       533    13.0     13.0          0                N   
1936757    SAT  ATL       874     8.0     11.0          0                N   

         Diverted  CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  \
0               0           NaN           NaN       NaN            NaN   
1               0           NaN           NaN       NaN            NaN   
2               0           NaN           NaN       NaN            NaN   
3               0           2.0           0.0       0.0            0.0   
4               0           NaN           NaN       NaN    

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.head()

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955   
1           1  2008      1           3          4    754.0         735   
2           2  2008      1           3          4    628.0         620   
3           4  2008      1           3          4   1829.0        1755   
4           5  2008      1           3          4   1940.0        1915   

   ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0   2211.0        2225            WN        335  N712SW              128.0   
1   1002.0        1000            WN       3231  N772SW              128.0   
2    804.0         750            WN        448  N428WN               96.0   
3   1959.0        1925            WN       3920  N464WN               90.0   
4   2121.0        2110            WN        378  N726SW              101.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   
4           115.0     87.0      11.0      25.0    IND  JAX       688     4.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                N         0           NaN           NaN   
1     10.0          0                N         0           NaN           NaN   
2     17.0          0                N         0           NaN           NaN   
3     10.0          0                N         0           2.0           0.0   
4     10.0          0                N         0           NaN           NaN   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       NaN            NaN                NaN  
1       NaN            NaN                NaN  
2       NaN            NaN                NaN  
3       0.0            0.0               32.0  
4       NaN            NaN                NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype  
---  ------             -----  
 0   Unnamed: 0         int64  
 1   Year               int64  
 2   Month              int64  
 3   DayofMonth         int64  
 4   DayOfWeek          int64  
 5   DepTime            float64
 6   CRSDepTime         int64  
 7   ArrTime            float64
 8   CRSArrTime         int64  
 9   UniqueCarrier      object 
 10  FlightNum          int64  
 11  TailNum            object 
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object 
 18  Dest               object 
 19  Distance           int64  
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64  
 23  CancellationCode   object 
 24  Diverted           int64  
 25  CarrierDelay      

In [6]:
df.CancellationCode.unique()

array(['N', 'A', 'B', 'C'], dtype=object)

In [7]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [8]:
df.describe().T

count          mean           std     min        25%  \
Unnamed: 0         1936758.0  3.341651e+06  2.066065e+06     0.0  1517452.5   
Year               1936758.0  2.008000e+03  0.000000e+00  2008.0     2008.0   
Month              1936758.0  6.111106e+00  3.482546e+00     1.0        3.0   
DayofMonth         1936758.0  1.575347e+01  8.776272e+00     1.0        8.0   
DayOfWeek          1936758.0  3.984827e+00  1.995966e+00     1.0        2.0   
DepTime            1936758.0  1.518534e+03  4.504853e+02     1.0     1203.0   
CRSDepTime         1936758.0  1.467473e+03  4.247668e+02     0.0     1135.0   
ArrTime            1929648.0  1.610141e+03  5.481781e+02     1.0     1316.0   
CRSArrTime         1936758.0  1.634225e+03  4.646347e+02     0.0     1325.0   
FlightNum          1936758.0  2.184263e+03  1.944702e+03     1.0      610.0   
ActualElapsedTime  1928371.0  1.333059e+02  7.206007e+01    14.0       80.0   
CRSElapsedTime     1936560.0  1.343027e+02  7.134144e+01   -25.0       82.0   
AirTime            1928371.0  1.082771e+02  6.864261e+01     0.0       58.0   
ArrDelay           1928371.0  4.219988e+01  5.678472e+01  -109.0        9.0   
DepDelay           1936758.0  4.318518e+01  5.340250e+01     6.0       12.0   
Distance           1936758.0  7.656862e+02  5.744797e+02    11.0      338.0   
TaxiIn             1929648.0  6.812975e+00  5.273595e+00     0.0        4.0   
TaxiOut            1936303.0  1.823220e+01  1.433853e+01     0.0       10.0   
Cancelled          1936758.0  3.268348e-04  1.807562e-02     0.0        0.0   
Diverted           1936758.0  4.003598e-03  6.314722e-02     0.0        0.0   
CarrierDelay       1247488.0  1.917940e+01  4.354621e+01     0.0        0.0   
WeatherDelay       1247488.0  3.703571e+00  2.149290e+01     0.0        0.0   
NASDelay           1247488.0  1.502164e+01  3.383305e+01     0.0        0.0   
SecurityDelay      1247488.0  9.013714e-02  2.022714e+00     0.0        0.0   
LateAircraftDelay  1247488.0  2.529647e+01  4.205486e+01     0.0        0.0   

                         50%         75%        max  
Unnamed: 0         3242558.0  4972466.75  7009727.0  
Year                  2008.0     2008.00     2008.0  
Month                    6.0        9.00       12.0  
DayofMonth              16.0       23.00       31.0  
DayOfWeek                4.0        6.00        7.0  
DepTime               1545.0     1900.00     2400.0  
CRSDepTime            1510.0     1815.00     2359.0  
ArrTime               1715.0     2030.00     2400.0  
CRSArrTime            1705.0     2014.00     2400.0  
FlightNum             1543.0     3422.00     9742.0  
ActualElapsedTime      116.0      165.00     1114.0  
CRSElapsedTime         116.0      165.00      660.0  
AirTime                 90.0      137.00     1091.0  
ArrDelay                24.0       56.00     2461.0  
DepDelay                24.0       53.00     2467.0  
Distance               606.0      998.00     4962.0  
TaxiIn                   6.0        8.00      240.0  
TaxiOut                 14.0       21.00      422.0  
Cancelled                0.0        0.00        1.0  
Diverted                 0.0        0.00        1.0  
CarrierDelay             2.0       21.00     2436.0  
WeatherDelay             0.0        0.00     1352.0  
NASDelay                 2.0       15.00     1357.0  
SecurityDelay            0.0        0.00      392.0  
LateAircraftDelay        8.0       33.00     1316.0

In [9]:
df[df['ArrDelay']<15].shape[0]

680883

In [10]:
df.Cancelled.value_counts()

0    1936125
1        633
Name: Cancelled, dtype: int64

In [11]:
df.Diverted.value_counts()

0    1929004
1       7754
Name: Diverted, dtype: int64

In [12]:
df.Diverted.value_counts()[1] + df.Cancelled.value_counts()[1]

8387

In [13]:
df['ArrDelay'].isnull().sum()

8387

In [21]:
df.ArrDelay[df['ArrDelay']<15] = 0

C:\Users\alana.olivieri\AppData\Local\Temp\ipykernel_12876\831260710.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.ArrDelay[df['ArrDelay']<15] = 0


In [22]:
df[df['ArrDelay']<15]

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955   
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
4                 5  2008      1           3          4   1940.0        1915   
6                10  2008      1           3          4    706.0         700   
...             ...   ...    ...         ...        ...      ...         ...   
1936739     7009646  2008     12          13          6   1100.0        1045   
1936740     7009652  2008     12          13          6   1200.0        1150   
1936750     7009702  2008     12          13          6   1531.0        1522   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  \
0         2211.0        2225            WN        335  N712SW   
1         1002.0        1000            WN       3231  N772SW   
2          804.0         750            WN        448  N428WN   
4         2121.0        2110            WN        378  N726SW   
6          916.0         915            WN        100  N690SW   
...          ...         ...           ...        ...     ...   
1936739   1350.0        1347            DL       1530  N920DL   
1936740   1924.0        1921            DL       1538  N6710E   
1936750   1822.0        1823            DL       1612  N916DN   
1936756   1446.0        1437            DL       1639  N646DL   
1936757   1413.0        1418            DL       1641  N908DL   

         ActualElapsedTime  CRSElapsedTime  AirTime  ArrDelay  DepDelay  \
0                    128.0           150.0    116.0       0.0       8.0   
1                    128.0           145.0    113.0       0.0      19.0   
2                     96.0            90.0     76.0       0.0       8.0   
4                    101.0           115.0     87.0       0.0      25.0   
6                    130.0           135.0    106.0       0.0       6.0   
...                    ...             ...      ...       ...       ...   
1936739              110.0           122.0     91.0       0.0      15.0   
1936740              264.0           271.0    238.0       0.0      10.0   
1936750              111.0           121.0     88.0       0.0       9.0   
1936756              115.0           117.0     89.0       0.0      11.0   
1936757              123.0           135.0    104.0       0.0       7.0   

        Origin Dest  Distance  TaxiIn  TaxiOut  Cancelled CancellationCode  \
0          IAD  TPA       810     4.0      8.0          0                N   
1          IAD  TPA       810     5.0     10.0          0                N   
2          IND  BWI       515     3.0     17.0          0                N   
4          IND  JAX       688     4.0     10.0          0                N   
6          IND  MCO       828     5.0     19.0          0                N   
...        ...  ...       ...     ...      ...        ...              ...   
1936739    MCI  ATL       692     7.0     12.0          0                N   
1936740    PDX  ATL      2172    11.0     15.0          0                N   
1936750    MCI  ATL       692     9.0     14.0          0                N   
1936756    IAD  ATL       533    13.0     13.0          0                N   
1936757    SAT  ATL       874     8.0     11.0          0                N   

         Diverted  CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  \
0               0           NaN           NaN       NaN            NaN   
1               0           NaN           NaN       NaN            NaN   
2               0           NaN           NaN       NaN            NaN   
4               0           NaN           NaN       NaN            NaN   
6               0           NaN           NaN       NaN    

In [23]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [24]:
df = df[(df.Cancelled == 0) & (df.Diverted == 0)]

In [25]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

In [26]:
df.duplicated().sum()

0

In [28]:
df_limpio = df[['FlightNum', 'AirTime', 'ArrDelay', 'UniqueCarrier']]
df_limpio.head()

FlightNum  AirTime  ArrDelay UniqueCarrier
0        335    116.0       0.0            WN
1       3231    113.0       0.0            WN
2        448     76.0       0.0            WN
3       3920     77.0      34.0            WN
4        378     87.0       0.0            WN

In [37]:
df_sample = df_limpio.sample(n=200000, random_state=12)

In [38]:
df_sample.head()

FlightNum  AirTime  ArrDelay UniqueCarrier
1535131       2208     41.0       0.0            WN
221646        2292     91.0      17.0            XE
1849672       5630     52.0      78.0            EV
1354141       4524    117.0     134.0            EV
1935802        723    142.0      62.0            DL

In [45]:
df_sample.groupby('UniqueCarrier')['ArrDelay'].mean().sort_values(ascending=False).head(10)

UniqueCarrier
B6    54.465780
YV    53.368527
OH    50.989251
XE    48.544366
UA    47.199261
9E    46.961753
AA    45.972467
EV    45.780170
MQ    44.263850
OO    43.521909
Name: ArrDelay, dtype: float64

In [46]:
df_sample.groupby('UniqueCarrier')['ArrDelay'].sum().sort_values(ascending=False).head(10)

UniqueCarrier
WN    1104206.0
AA     908324.0
UA     689534.0
MQ     643198.0
OO     602909.0
XE     514813.0
DL     448245.0
CO     419793.0
EV     393389.0
YV     372032.0
Name: ArrDelay, dtype: float64

In [47]:
df_sample.groupby('UniqueCarrier')['ArrDelay'].count().sort_values(ascending=False).head(10)

UniqueCarrier
WN    39079
AA    19758
UA    14609
MQ    14531
OO    13853
DL    11799
XE    10605
CO    10335
US    10164
EV     8593
Name: ArrDelay, dtype: int64

In [48]:
df_sample['Delayed'] = df_sample['ArrDelay'] >= 15

In [49]:
df_sample.head()

FlightNum  AirTime  ArrDelay UniqueCarrier  Delayed
1535131       2208     41.0       0.0            WN    False
221646        2292     91.0      17.0            XE     True
1849672       5630     52.0      78.0            EV     True
1354141       4524    117.0     134.0            EV     True
1935802        723    142.0      62.0            DL     True

In [50]:
df_sample.groupby('UniqueCarrier')['Delayed'].mean().sort_values(ascending=False).head(10)

UniqueCarrier
OH    0.764096
YV    0.760866
NW    0.700945
9E    0.699220
AA    0.696326
XE    0.692975
EV    0.691609
B6    0.691489
MQ    0.687565
UA    0.678349
Name: Delayed, dtype: float64

In [51]:
df_sample.groupby('UniqueCarrier')['Delayed'].sum().sort_values(ascending=False).head(10)

UniqueCarrier
WN    21096
AA    13758
MQ     9991
UA     9910
OO     9327
DL     7481
XE     7349
US     6269
CO     6154
EV     5943
Name: Delayed, dtype: int64